export const stats = [
  { label: "Royal Revenue", value: "$248,910", delta: "+12.4%", trend: "up" as const },
  { label: "Active Subjects", value: "18,432", delta: "+3.2%", trend: "up" as const },
  { label: "Court Sessions", value: "1,204", delta: "-1.1%", trend: "down" as const },
  { label: "Treasury Yield", value: "94.8%", delta: "+0.6%", trend: "up" as const },
];

export const revenueSeries = [
  { month: "Jan", revenue: 32, expenses: 18 },
  { month: "Feb", revenue: 41, expenses: 22 },
  { month: "Mar", revenue: 38, expenses: 20 },
  { month: "Apr", revenue: 52, expenses: 28 },
  { month: "May", revenue: 61, expenses: 30 },
  { month: "Jun", revenue: 74, expenses: 36 },
  { month: "Jul", revenue: 82, expenses: 41 },
  { month: "Aug", revenue: 78, expenses: 39 },
  { month: "Sep", revenue: 95, expenses: 44 },
];

export const decrees = [
  {
    id: "DCR-3041",
    title: "Trade tariff revision",
    owner: "Lady Adelaide",
    status: "Sealed",
    date: "Mar 12",
  },
  {
    id: "DCR-3042",
    title: "Harvest festival budget",
    owner: "Sir Aldwin",
    status: "Pending",
    date: "Mar 14",
  },
  {
    id: "DCR-3043",
    title: "Northern fort restoration",
    owner: "Duke Cassian",
    status: "Review",
    date: "Mar 15",
  },
  {
    id: "DCR-3044",
    title: "Royal scholarship program",
    owner: "Dame Iris",
    status: "Sealed",
    date: "Mar 17",
  },
  {
    id: "DCR-3045",
    title: "Maritime patrol charter",
    owner: "Lord Edric",
    status: "Draft",
    date: "Mar 18",
  },
];

export const activities = [
  { who: "Lady Adelaide", what: "sealed a decree", when: "2m ago" },
  { who: "Duke Cassian", what: "left a remark on Northern fort", when: "1h ago" },
  { who: "Dame Iris", what: "approved scholarship funding", when: "3h ago" },
  { who: "Sir Aldwin", what: "drafted the harvest agenda", when: "Yesterday" },
];

import type { Assignment } from "@/models/assignments";

export const assignments: Assignment[] = [
  {
    id: "ASG-2001",
    title: "Prepare quarterly treasury report",
    description: "Compile and analyze quarterly financial statements for the Royal Treasury",
    assignedTo: "Lady Adelaide",
    assignedBy: "Duke Cassian",
    status: "In Progress",
    priority: "High",
    dueDate: "Mar 20, 2024",
    createdDate: "Mar 05, 2024",
    tags: ["Finance", "Urgent"],
  },
  {
    id: "ASG-2002",
    title: "Court ceremony arrangements",
    description: "Coordinate logistics and guest list for the spring royal court ceremony",
    assignedTo: "Sir Aldwin",
    assignedBy: "Dame Iris",
    status: "Pending",
    priority: "High",
    dueDate: "Mar 25, 2024",
    createdDate: "Mar 08, 2024",
    tags: ["Events", "Planning"],
  },
  {
    id: "ASG-2003",
    title: "Northern territories inspection",
    description: "Conduct a thorough inspection of Northern fort defenses and garrison readiness",
    assignedTo: "Duke Cassian",
    assignedBy: "Lord Edric",
    status: "Completed",
    priority: "Medium",
    dueDate: "Mar 18, 2024",
    createdDate: "Mar 01, 2024",
    completedDate: "Mar 17, 2024",
    tags: ["Military", "Inspection"],
  },
  {
    id: "ASG-2004",
    title: "Draft maritime trade agreement",
    description: "Negotiate and draft new maritime trade agreement with neighboring kingdoms",
    assignedTo: "Lord Edric",
    assignedBy: "Duke Cassian",
    status: "In Progress",
    priority: "Critical",
    dueDate: "Mar 22, 2024",
    createdDate: "Mar 10, 2024",
    tags: ["Diplomacy", "Trade"],
  },
  {
    id: "ASG-2005",
    title: "Royal scholarship fund allocation",
    description: "Review and allocate scholarship funds to qualifying candidates",
    assignedTo: "Dame Iris",
    assignedBy: "Lady Adelaide",
    status: "Review",
    priority: "Medium",
    dueDate: "Mar 19, 2024",
    createdDate: "Mar 12, 2024",
    tags: ["Education", "Approval Pending"],
  },
  {
    id: "ASG-2006",
    title: "Harvest festival planning",
    description: "Oversee organization and budget management for annual harvest festival",
    assignedTo: "Sir Aldwin",
    assignedBy: "Duke Cassian",
    status: "Pending",
    priority: "Low",
    dueDate: "Apr 15, 2024",
    createdDate: "Mar 14, 2024",
    tags: ["Events", "Long-term"],
  },
];
